/**
 * Unycross-Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrackDto { 
    id?: number;
    name?: string | null;
    description?: string | null;
    longitude?: string | null;
    latitude?: string | null;
    slug?: string | null;
    status?: string | null;
    rating?: string | null;
    terrain?: string | null;
}

